const viewPanel = document.querySelector("#viewPanel");
const viewTitle = document.querySelector("#viewTitle");
const navLinks = [...document.querySelectorAll("[data-view]")];

const views = {
  home: {
    title: "Explorer",
    kicker: "Historical resonance engine",
    summary:
      "The first screen is the working research desk: planetary wheel, active cycles, similar epochs, matched events, context events, sources, confidence and why this match.",
    cards: [
      {
        label: "Core workflow",
        title: "Explorer",
        body: "Enter a date or year, inspect dominant cycles, compare historical echoes and keep sourced events separate from broader context.",
        badges: ["date input", "similar epochs", "why this match"],
      },
      {
        label: "Editorial layer",
        title: "Insights",
        body: "AI-assisted research notes can be drafted from engine output, then human reviewed before publishing.",
        badges: ["Generated by Astro Global", "Human reviewed", "Sources included"],
      },
      {
        label: "Public trust",
        title: "Transparency",
        body: "The product explains data limits, confidence, source quality and the rule that similarity is not prediction.",
        badges: ["confidence", "source archive", "limits"],
      },
    ],
  },
  today: {
    title: "Today",
    kicker: "Active sky, no prediction",
    summary:
      "Today focuses on what is astrologically active now: current planetary positions, primary cycles and near exact configurations.",
    cards: [
      {
        label: "Active cycle",
        title: "Saturn - Neptune",
        body: "Conjunction window with historical resonance around 1989 and 2026. Displayed as active context, not a forecast.",
        badges: ["0° 11′ orb", "~36 years", "not prediction"],
      },
      {
        label: "Current sky",
        title: "Planetary positions",
        body: "A compact daily panel for sign, degree, active aspects and confidence warnings when data coverage is thin.",
        badges: ["planet wheel", "aspects", "coverage"],
      },
      {
        label: "Next contact",
        title: "20 February 2026",
        body: "Calendar-ready marker for the next exact Saturn-Neptune contact, with explanatory context and sources.",
        badges: ["calendar", "exact date", "sources"],
      },
    ],
  },
  explorer: {
    title: "Explorer",
    kicker: "Date and year research desk",
    summary:
      "The Explorer shell is built around a date or year query and shows planetary layout, dominant cycles, similar epochs and event evidence.",
    cards: [
      {
        label: "Matched events",
        title: "Direct evidence",
        body: "Point events remain visible as matched events: declarations, treaties, starts and precise historical markers.",
        badges: ["matched events", "source quality", "confidence"],
      },
      {
        label: "Context events",
        title: "Long processes",
        body: "Broad intellectual, social and geopolitical movements appear as context events instead of crowding direct matches.",
        badges: ["context events", "long process", "separated"],
      },
      {
        label: "Why this match",
        title: "Traceable reasoning",
        body: "The interface reserves space for cycle overlap, score components, event windows and source notes.",
        badges: ["dominant cycles", "similar epochs", "why this match"],
      },
    ],
  },
  compare: {
    title: "Compare",
    kicker: "Two eras side by side",
    summary:
      "Compare is for pairs like 2026 vs 1789, 1968 vs 1848 and 1989 vs 2020: shared cycles, differences, themes and confidence.",
    cards: [
      {
        label: "2026 vs 1789",
        title: "Systemic pressure",
        body: "Shared slow-cycle emphasis with different historical containers: modern global order versus revolutionary France.",
        badges: ["shared cycles", "differences", "confidence 72%"],
      },
      {
        label: "1968 vs 1848",
        title: "Mass movement echoes",
        body: "Both sides can show civic unrest, generational pressure and reform language without claiming repetition.",
        badges: ["motifs", "events both sides", "not identical"],
      },
      {
        label: "1989 vs 2020",
        title: "Order transition",
        body: "A comparison layout for institutional rupture, public health shocks, social adaptation and source-backed caveats.",
        badges: ["themes", "matched events", "context"],
      },
    ],
  },
  calendar: {
    title: "Calendar",
    kicker: "Configuration timeline",
    summary:
      "Calendar shows active and upcoming configurations: what is astrologically active, when it peaks and where context begins.",
    cards: [
      {
        label: "Active now",
        title: "Saturn - Neptune window",
        body: "Current configuration panel with exact dates, orb, cycle length and historical references.",
        badges: ["active cycle", "exact contacts", "no prediction"],
      },
      {
        label: "Upcoming",
        title: "Jupiter - Uranus",
        body: "Near-term cycle view for upcoming configurations and previous occurrences.",
        badges: ["timeline", "cycle range", "context"],
      },
      {
        label: "Archive",
        title: "1200 - 2200 view",
        body: "Long-horizon timeline for research scanning, with filters for aspect type and cycle families.",
        badges: ["filters", "aspect types", "research"],
      },
    ],
  },
  insights: {
    title: "Insights",
    kicker: "AI-assisted research notes",
    summary:
      "Insights are engine-supported articles, separate from the personal blog. Each article keeps provenance and review status visible.",
    cards: [
      {
        label: "Cycle report",
        title: "Saturn-Neptune: historical analogies",
        body: "Generated from engine results, source-backed event sets and editorial review.",
        badges: ["Generated by Astro Global", "Human reviewed", "Sources included"],
      },
      {
        label: "Resonance article",
        title: "1789 and 2026",
        body: "A structured note on similarities, differences, confidence and limits.",
        badges: ["Assisted by Astro Global", "confidence", "limits"],
      },
      {
        label: "Current sky",
        title: "What the active layout shows",
        body: "A calm public-facing explanation of current configurations without prophecy language.",
        badges: ["research note", "not prediction", "review needed"],
      },
    ],
  },
  library: {
    title: "Library",
    kicker: "Knowledge base",
    summary:
      "Library is the educational and documentation layer: cycles, aspects, epochs, event database, source archive and explainers.",
    cards: [
      {
        label: "Cycles",
        title: "Planetary cycle dictionary",
        body: "Saturn-Neptune, Jupiter-Uranus, Pluto-node and other cycle families with cycle length and historical examples.",
        badges: ["cycles", "definitions", "examples"],
      },
      {
        label: "Events",
        title: "Event database",
        body: "A browsable public layer for dated events, precision, category, sources and confidence notes.",
        badges: ["event archive", "sources", "precision"],
      },
      {
        label: "Explain",
        title: "Aspect dictionary",
        body: "Plain-language explainers for conjunctions, squares, trines, sextiles and oppositions.",
        badges: ["aspects", "education", "documentation"],
      },
    ],
  },
  blog: {
    title: "Blog",
    kicker: "Human essays",
    summary:
      "Blog is separate from AI-assisted Insights: personal observations, manual interpretation and educational writing.",
    cards: [
      {
        label: "Manual",
        title: "Personal observation",
        body: "A dedicated space for authored posts, voice and interpretation outside the generated research-note pipeline.",
        badges: ["manual text", "author voice", "editorial"],
      },
      {
        label: "Education",
        title: "How to read cycles",
        body: "Accessible articles that teach the system vocabulary without mixing it with generated reports.",
        badges: ["learning", "cycles", "human written"],
      },
      {
        label: "Notes",
        title: "Field journal",
        body: "Short entries, reflections and curated observations that do not need the formal research-note format.",
        badges: ["journal", "observations", "separate from AI"],
      },
    ],
  },
  contact: {
    title: "Contact",
    kicker: "Request analysis",
    summary:
      "Contact starts simple: name, email, topic, message, optional birth data and consent before private analysis workflows.",
    form: true,
    cards: [
      {
        label: "Private analysis",
        title: "Optional birth data",
        body: "Date, time and place can be collected only when the user explicitly requests a private analysis.",
        badges: ["optional", "consent", "privacy"],
      },
      {
        label: "Requests",
        title: "Simple intake",
        body: "The first public version can use a lean form before any account system or admin dashboard exists.",
        badges: ["name", "email", "message"],
      },
    ],
  },
};

function setActiveView(viewName) {
  const view = views[viewName] ?? views.home;
  viewTitle.textContent = view.title;
  viewPanel.innerHTML = renderView(view);
  document.body.dataset.view = viewName;

  for (const link of navLinks) {
    link.classList.toggle("active", link.dataset.view === viewName);
  }

  const route = document.querySelector(`[data-view="${viewName}"]`)?.dataset.route;
  if (route) {
    history.replaceState({ view: viewName }, "", `#${route === "/" ? "home" : route.slice(1)}`);
  }

  const contactForm = viewPanel.querySelector("#contactForm");
  if (contactForm) {
    contactForm.addEventListener("submit", (event) => {
      event.preventDefault();
      viewPanel.querySelector("#contactState").textContent = "Draft saved in this shell";
    });
  }
}

function renderView(view) {
  const cardHtml = view.cards.map(renderCard).join("");
  const formHtml = view.form ? renderContactForm() : "";
  return `
    <div class="view-intro">
      <p class="eyebrow">${view.kicker}</p>
      <p>${view.summary}</p>
    </div>
    <div class="research-grid">${cardHtml}</div>
    ${formHtml}
  `;
}

function renderCard(card) {
  return `
    <article class="research-card">
      <p class="card-label">${card.label}</p>
      <h3>${card.title}</h3>
      <p>${card.body}</p>
      <div class="badge-row">
        ${card.badges.map((badge) => `<span class="status-pill">${badge}</span>`).join("")}
      </div>
    </article>
  `;
}

function renderContactForm() {
  return `
    <form class="contact-form" id="contactForm">
      <label>
        Name
        <input name="name" autocomplete="name" />
      </label>
      <label>
        Email
        <input name="email" type="email" autocomplete="email" />
      </label>
      <label>
        Topic
        <select name="topic">
          <option>Private analysis</option>
          <option>Research question</option>
          <option>Editorial contact</option>
        </select>
      </label>
      <label class="wide-field">
        Message
        <textarea name="message" rows="4"></textarea>
      </label>
      <label>
        Birth date
        <input name="birthDate" type="date" />
      </label>
      <label>
        Birth time
        <input name="birthTime" type="time" />
      </label>
      <label class="wide-field">
        Birth place
        <input name="birthPlace" />
      </label>
      <label class="consent-field wide-field">
        <input name="consent" type="checkbox" />
        <span>I consent to processing this request.</span>
      </label>
      <button class="primary-action" type="submit">Submit request</button>
      <span class="form-state" id="contactState" aria-live="polite"></span>
    </form>
  `;
}

function viewFromHash() {
  const value = window.location.hash.replace(/^#\/?/, "") || "home";
  return value === "" ? "home" : value;
}

document.addEventListener("click", (event) => {
  const trigger = event.target.closest("[data-view]");
  if (!trigger) {
    return;
  }
  event.preventDefault();
  setActiveView(trigger.dataset.view);
});

window.addEventListener("hashchange", () => setActiveView(viewFromHash()));

setActiveView(viewFromHash());
